export const PlayerData = [
  {
    id: 1,
    picture: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3134881.png",
    player_api_id: 276,
    team_api_id: 17,
    first_name: "Stanley",
    last_name: "Johnson",
    points: 6.7,
    assists: 1.7,
    rebounds: 3.2,
    steals: 0.9,
    blocks: 0.3,
    turnovers: 0.7,
    field_goal_percentage: 46.6,
    free_throw_percentage: 71.6,
    three_points_made: 0.7
  },
  {
    id: 2,
    picture: "https://a1.espncdn.com/combiner/i?img=%2Fi%2Fheadshots%2Fnba%2Fplayers%2Ffull%2F4066262.png",
    player_api_id: 842,
    team_api_id: 17,
    first_name: "Malik",
    last_name: "Monk",
    points: 13.8,
    assists: 2.9,
    rebounds: 3.4,
    steals: 0.4,
    blocks: 0.8,
    turnovers: 1.6,
    field_goal_percentage: 47.3,
    free_throw_percentage: 79.5,
    three_points_made: 2.3
  },
  {
    id: 3,
    picture: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4396991.png",
    player_api_id: 1867,
    team_api_id: 17,
    first_name: "Talen",
    last_name: "Horton-Tucker",
    points: 10,
    assists: 2.7,
    rebounds: 3.2,
    steals: 1,
    blocks: 0.5,
    turnovers: 1.4,
    field_goal_percentage: 41.6,
    free_throw_percentage: 80,
    three_points_made: 0.8
  },
  {
    id: 4,
    picture: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066457.png",
    player_api_id: 2845,
    team_api_id: 17,
    first_name: "Austin",
    last_name: "Reeves",
    points: 7.3,
    assists: 1.8,
    rebounds: 3.2,
    steals: 0.5,
    blocks: 0.3,
    turnovers: 0.7,
    field_goal_percentage: 45.9,
    free_throw_percentage: 83.9,
    three_points_made: 0.9
  },
  {
    id: 5,
    picture: "https://a.espncdn.com/i/headshots/nba/players/full/3468.png",
    player_api_id: 544,
    team_api_id: 17,
    first_name: "Russel",
    last_name: "Westbrook",
    points: 18.5,
    assists: 7.1,
    rebounds: 7.4,
    steals: 1,
    blocks: 0.3,
    turnovers: 3.8,
    field_goal_percentage: 44.4,
    free_throw_percentage: 66.7,
    three_points_made: 1
  },
  {
    id: 6,
    picture: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4240.png",
    player_api_id: 68,
    team_api_id: 17,
    first_name: "Avery",
    last_name: "Bradley",
    points: 6.4,
    assists: 0.8,
    rebounds: 2.2,
    steals: 0.9,
    blocks: 0,
    turnovers: 0.6,
    field_goal_percentage: 42.3,
    free_throw_percentage: 88.9,
    three_points_made: 1.3
  },
  {
    id: 7,
    picture: "https://a.espncdn.com/i/headshots/nba/players/full/6583.png",
    player_api_id: 126,
    team_api_id: 17,
    first_name: "Anthony",
    last_name: "Davis",
    points: 23.2,
    assists: 3.1,
    rebounds: 9.9,
    steals: 1.2,
    blocks: 2.3,
    turnovers: 2.1,
    field_goal_percentage: 53.2,
    free_throw_percentage: 71.3,
    three_points_made: 0.3
  },
  {
    id: 8,
    picture: "https://a.espncdn.com/i/headshots/nba/players/full/1966.png",
    player_api_id: 265,
    team_api_id: 17,
    first_name: "LeBron",
    last_name: "James",
    points: 30.3,
    assists: 6.2,
    rebounds: 8.2,
    steals: 1.3,
    blocks: 1.1,
    turnovers: 3.5,
    field_goal_percentage: 52.4,
    free_throw_percentage: 75.6,
    three_points_made: 0.7
  },
  {
    id: 9,
    picture: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2426.png",
    player_api_id: 21,
    team_api_id: 17,
    first_name: "Carmelo",
    last_name: "Anthony",
    points: 13.3,
    assists: 1,
    rebounds: 4.2,
    steals: 0.7,
    blocks: 0.8,
    turnovers: 0.9,
    field_goal_percentage: 44.1,
    free_throw_percentage: 83,
    three_points_made: 2.2
  },
  {
    id: 10,
    picture: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3134881.png",
    player_api_id: 23,
    team_api_id: 17,
    first_name: "Trevor",
    last_name: "Ariza",
    points: 4,
    assists: 1.1,
    rebounds: 3.4,
    steals: 0.5,
    blocks: 0.3,
    turnovers: 0.5,
    field_goal_percentage: 33.3,
    free_throw_percentage: 55.6,
    three_points_made: 0.8
  }
]